### ISSUE TITLE
[Feature] Json logging handler

### ISSUE THREAD

**Issue by benzvan** [gorilla/handlers#218]
I'd love to be able to output json-formatted logs in with the same fields as common. This would make logs more easily parseable and searchable in GCP's log viewer and other log systems like ELK, etc.

**Comment by elithrar** [comment]
You should read
https://blog.questionable.services/article/guide-logging-middleware-go/ :-)

This library is unlikely to “do everything” - it’s a good place for folks
to get started but logging turns out to be a kitchen sink feature - there’s
no way to make everyone happy. We’ll keep a simple logging handler and let
others copy, fork or write their own as their needs grow.

**Comment by benzvan** [comment]
Thanks! I'll take a look.
