### ISSUE TITLE
CompressHandler: Write on hijacked connection error

### ISSUE THREAD

**Issue by nwidger** [gorilla/handlers#46]
If the ResponseWriter I pass to handlers.CompressHandler support http.Hijacker gets hijacked, I'll often see this error come out of my server:

```
2015/08/25 09:20:41 server.go:1934: http: response.Write on hijacked connection
```

I believe this is caused by the deferred Close calls on the gzip/flat Writer's.  The documentation for both says that calling Close will flush any pending data, which might generate calls to Write.  I believe the fix is to set a flag if Hijack is called on the connection, and only call Call on the gzip/flat Writer if the connection was not hijacked.

**Comment by kisielk** [comment]
Do you have any example code that can reproduce?

**Comment by elithrar** [comment]
Yep, if you can supply an example it'll help show where a fix can be made. I'm potentially refactoring the internals of CompressHandler under https://github.com/gorilla/handlers/issues/44 which might make this easier.

Note that we *must* call `gw.Close()` else the gzip written out will be incomplete (malformed). Since you can't call that yourself we need to either detect the `http.Hijacker` ahead of time and *not* gzip the response (which may be opaque/confusing), or devise another way (if possible) that won't write to the hijacked writer until later (?).

**Comment by nwidger** [comment]
Running this with `go run` produces the `response.Write on hijacked connection` error consistently for me:

http://play.golang.org/p/qn9ZQY6xHh

**Comment by nwidger** [comment]
Something like this might work:

http://play.golang.org/p/GF_AmCP2-6

We implement our own `Hijack` method which checks if the `ResponseWriter` supports the `Hijacker` interface.  If so, reset the flate/gzip writer to write to `ioutil.Discard`.  This way, the deferred `Close` calls can still happen without ending up writing to a hijacked connection.  Thoughts?

**Comment by nwidger** [comment]
Perhaps this is a bit better as we only reset the flate/gzip writer is the `Hijack` call actually succeeds:

http://play.golang.org/p/80HukFxfs4

**Comment by nwidger** [comment]
Just wondering if there's any update on this?

**Comment by elithrar** [comment]
I'm open to a PR on this if you think you can tackle it: once we have a PR
(with tests) we can make sure we don't break existing applications.

**Comment by nwidger** [comment]
So you agree that this is a legitimate issue?

**Comment by elithrar** [comment]
Sorry for the slow reply: I agree insomuch that we can fix the problem without breaking the API or changing obvious behaviour for existing users.
