### ISSUE TITLE
ProxyHeaders uses X-Forwarded-Scheme, not X-Forwarded-Proto

### ISSUE THREAD

**Issue by jgraettinger** [gorilla/handlers#79]
RFC 7239 refers to X-Forwarded-Proto, as do the GoDocs of this package. 

However, [proxy_headers.go actually uses X-Forwarded-Scheme](https://github.com/gorilla/handlers/blob/master/proxy_headers.go#L13).

**Comment by elithrar** [comment]
You're correct, and we should have been using that (although `Scheme` is incredibly popular as well). Given that users of this package are relying on `X-Forwarded-Scheme`, we either:

a) Update the docs and make no code changes (the bug lies in the docs)
b) Add a second header, leaving `X-Forwarded-Scheme` as-is.

I'd need to do some work to see how widely this package's `X-Forwarded-Scheme` is depended upon by applications (via GitHub/Sourcegraph search) before making any breaking change.

**Comment by jgraettinger** [comment]
I've actually never seen X-Forwarded-Scheme, though I'll take your word for it. Note that [Heroku](https://devcenter.heroku.com/articles/http-routing), [AWS](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html) and [Google Cloud Platform](https://cloud.google.com/compute/docs/load-balancing/http/) all use `X-Forwarded-Proto` (and not `-Scheme`) in their HTTP load balancing service. I think that effectively rules out "a". "b" sounds like the right move to me.

**Comment by elithrar** [comment]
Correct, but Scheme still sees a lot of use (Scheme has more Google hits).
Would have been great to have this as Proto from the start, but that's
software.

You're welcome to submit a PR for option b) else I will fix it this week.
